better async effects
reactive-python/reactpy pull request #1169
Opened 2023-12-09 18:46 UTC by rmorshea

<sub>By submitting this pull request you agree that all contributions to this project are made under the MIT license.</sub>

## Issues

Closes: https://github.com/reactive-python/reactpy/issues/956

## Solution

Effects can now be defines as sync or async generators (more info in [the docs](https://github.com/rmorshea/reactpy/blob/af162be9960751c2dda9be7e7b97d367597df111/docs/source/reference/hooks-api.rst?plain=1#L87-L241)):

```python
@use_effect
def my_effect():
    conn = open_connection()
    try:
        # do something with the connection
        yield
    finally:
        conn.close()

@use_effect
async def my_effect():
    conn = await open_connection()
    try:
        # do something with the connection
        yield
    finally:
        await conn.close()
```

_Note: this contains a subset of the changes originally created in https://github.com/reactive-python/reactpy/pull/1093_

## Checklist

- [x] Tests have been included for all bug fixes or added functionality.
- [x] The `changelog.rst` has been updated with any significant changes.

2023-12-10 06:31 UTC, Archmonger commented
Will review on Monday. Not home at the moment.

2023-12-11 03:01 UTC, Archmonger requested changes
I like the flexibility of generator approach a lot more than our previously proposed `stop_event` interface.

But I do still think safeguards (`timeout`) need to be put in place for programmer error. We can't trust everyone to right perfect code, so we need to detect, warn, then mitigate programming flaws.

On a different note, now that our async function interface has deviated wildly from the sync equivalent, it's starting to become clear to me we shouldn't overload `use_effect` for async support any longer. We need to migrate towards a `use_async_effect` hook.

2023-12-11 03:01 UTC, Archmonger commented on docs/source/reference/hooks-api.rst
> +    using ``use_effect`` for the first time.
I don't like the idea of having no safeguard against this. An interface that doesn't protect against critical breaking behavior is usually the wrong interface.

Looks like we can leverage [`inspect.isgeneratorfunction`](https://docs.python.org/3/library/inspect.html#inspect.isgeneratorfunction) to auto-detect whether something yields.

2023-12-11 03:01 UTC, Archmonger commented on docs/source/reference/hooks-api.rst
> +    A component will be unable to render until all its outstanding effects have been
render -> re-render

2023-12-11 03:01 UTC, Archmonger commented on docs/source/reference/hooks-api.rst
> +simply write an async function.
`then you can simply write` -> `then you should use`

2023-12-11 03:01 UTC, Archmonger commented on src/py/reactpy/reactpy/core/_life_cycle_hook.py
> +            # potential memory leak if the task doesn't remove itself when complete
This comment needs a bit more description.

Is the memory leak due to our internal design, or due to user failure? Is the next LOC designed to prevent this issue, or is it the cause of this issue?

2023-12-11 03:01 UTC, Archmonger commented on src/py/reactpy/reactpy/core/_life_cycle_hook.py
> +        self._effect_tasks.update()
Is there any reason to call `update` here?

2023-12-11 03:01 UTC, Archmonger commented on src/py/reactpy/reactpy/core/hooks.py
> +        async def run_effect(stop: Event) -> None:
Does this function really need to be dynamically generated within `add_effect`? It would be more memory efficient to move `run_effect` outside of `add_effect`, and pass in all needed values via args.

Dynamically defined functions are generally a bad idea for any long-running Python code due to memory usage.

2023-12-11 03:01 UTC, Archmonger commented on src/py/reactpy/reactpy/core/hooks.py
> +                        "version of ReactPy.",
This needs to be mentioned in the changelog.

2023-12-11 03:01 UTC, Archmonger commented on docs/source/reference/hooks-api.rst
> +component re-renders:
The fact that returning cleanup functions will continue being allowed on sync effects (but not async effects) really makes me think we should commit to a `use_async_effect` hook.

It feels confusing to mandate two completely separate user interfaces within the same hook.

2023-12-12 04:02 UTC, rmorshea commented
I think we can have `use_async_effect` with a timeout parameter, but something I realized while working on this is that I don't think we can have a default. Having a default timeout trades concerns about responsiveness and hangs for memory leaks and unexpected behavior due to premature timeouts.

2023-12-12 04:28 UTC, Archmonger commented
Django has a similar timeout design for views. They have an arbitrary default of 20 seconds.
ASGI webservers also have similar timeouts, specifically related to `keep-alive` requests. Usually default of 5 seconds.

We just have to pick a "good enough" default, and trust the user to change it when needed.

2023-12-12 04:47 UTC, Archmonger commented
On that note, maybe `teardown_timeout` is a more appropriate name.

2023-12-12 18:31 UTC, rmorshea commented
> We just have to... trust the user to change it when needed.

Ultimately we have to trust the user to know what they're doing in some regard. Either we trust them to understand that if their effects don't end in a timely manner it will impact the responsiveness of components, or we trust that they understand how premature timeouts may cause memory leaks and unexpected behavior when resources aren't cleaned up. My intuition is that debugging issues with responsiveness will be much easier than trying to find the source of a memory leaks and orphaned resources.

2023-12-12 22:45 UTC, Archmonger commented
In the scenario where we catch and mitigate, it's we've caught the error and can log it. But in the scenario of user failure, it's a complete freeze with no user information.

Maybe we can default it to something large like 20 seconds? At that point we'd be 98% confident it's a programming failure and worth an `ERROR` log.

2023-12-14 18:19 UTC, Archmonger commented
I'm realizing both sync effects can be generators too.

Maybe we can stick with one `use_effect` but remove the ability to return a cancel function?

2023-12-17 23:38 UTC, Archmonger commented
In terms of whether we diverge to creating `use_async_effect`, this issue is also relevant: https://github.com/reactive-python/reactpy/issues/1136

In my mind, threading parameters should be unique to sync calls.

2024-10-31 00:52 UTC, Archmonger commented
Someone already thought of these issues and developed something relatively clean in the ReactJS space.

Ref: https://marmelab.com/blog/2023/01/11/use-async-effect-react.html#introducing-the-code-classlanguage-textuseasynceffectcode-hook

2025-02-03 05:53 UTC, Archmonger commented
Closing this since the PR is stale.

I will be spending some time to rethink this. This PR does significantly deviates us from ReactJS syntax, so perhaps it needs more thought.

2025-02-03 05:53 UTC, closed without merging